name: Buildimage

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          file: ./at-buildimage/Dockerfile
          push: true
          tags: |
            atsigncompany/buildimage:automated
            atsigncompany/buildimage:GHA${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}